# Generated by Django 3.0.8 on 2021-08-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
