# Generated by Django 3.0.8 on 2021-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
