# Generated by Django 3.0.8 on 2021-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210815_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sub_title', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
