# Generated by Django 3.0.8 on 2021-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210816_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='home',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
