# Generated by Django 3.0.8 on 2021-09-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210903_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='customer',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
