# Generated by Django 3.0.8 on 2021-09-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_favoriteitem_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='date_ordered',
            new_name='fav_date',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='transaction_id',
        ),
    ]
