# Generated by Django 3.0.8 on 2021-09-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210904_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='date_added',
            new_name='fav_added',
        ),
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='product',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='customer',
            new_name='user',
        ),
    ]
