# Generated by Django 3.0.8 on 2021-09-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210904_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='cust',
        ),
    ]
