# Generated by Django 3.0.8 on 2021-09-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210904_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='cust',
            new_name='customer',
        ),
    ]
