# Generated by Django 3.0.8 on 2021-09-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210904_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
