# Generated by Django 3.0.8 on 2021-09-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='score',
        ),
    ]
