# Generated by Django 3.0.8 on 2021-09-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rate_avg',
            field=models.FloatField(default=0),
        ),
    ]
