# Generated by Django 3.0.8 on 2021-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_store_rate_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rate_avg',
        ),
        migrations.AddField(
            model_name='store',
            name='avg_rate',
            field=models.IntegerField(default=0),
        ),
    ]
