# Generated by Django 3.0.8 on 2021-09-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210908_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='avg_rate',
        ),
        migrations.AddField(
            model_name='store',
            name='avg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
