# Generated by Django 3.0.8 on 2021-09-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210908_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Shoe'),
        ),
        migrations.AlterField(
            model_name='store',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
