# Generated by Django 3.0.8 on 2021-09-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210909_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe',
            new_name='Beauty',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shoe',
        ),
    ]
