# Generated by Django 3.0.8 on 2021-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210910_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='sub_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
