# Generated by Django 3.0.8 on 2021-09-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210910_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='beauty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Beauty'),
        ),
    ]
