# Generated by Django 3.0.8 on 2021-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_orderitem_beauty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sub_title', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='beauty',
        ),
    ]
