# Generated by Django 3.0.8 on 2021-09-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210910_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
